apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: sbom-eyecatcher-test
  janus-idp.io/tekton: sbom-eyecatcher-test
  backstage.io/kubernetes-id: sbom-eyecatcher-test
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: sbom-eyecatcher-test
resources:
- deployment.yaml
- route.yaml
- service.yaml
