apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: sbom-eyecatcher-test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sbom-eyecatcher-test 
  name: sbom-eyecatcher-test
spec:
  ports:
  - port: 8080 
    targetPort: 8080 
  selector:
    app.kubernetes.io/instance: sbom-eyecatcher-test 
